### ISSUE TITLE
Pasar a python 3

### ISSUE THREAD

**Issue by pabloalcain** [recalculando/salarios#2]
En las apuradas por subirlo, lo dejé escrito en Python 2. Si efectivamente votamos por escribir en python 3, hay que pasarlo antes de que sea demasiado grande y 2to3 siga funcionando bien.

**Comment by IonatanPerez** [comment]
Por ahora solo tuve problemas al correrlo en python 3 con la siguiente linea:

---> 28 agregado += pd.Timedelta('1 day') - pd.Timedelta('1 M')
'module' object has no attribute 'Timedelta'

Busque un poco y no encontre porque me pasa...

**Comment by pabloalcain** [comment]
sí, era por una versión vieja. ahora el script funciona bien en python3! =)
